// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Basic Test
---
*/
package cmds

import (
	"context"

	"github.com/365admin/koksmat-test1/execution"
	"github.com/365admin/koksmat-test1/utils"
)

func TestBasicPost(ctx context.Context, args []string) (*string, error) {

	result, pwsherr := execution.ExecutePowerShell("john", "*", "koksmat-test1", "50-test", "10-basic.ps1", "")
	if pwsherr != nil {
		return nil, pwsherr
	}
	utils.PrintSkip2FirstAnd2LastLines(string(result))
	return nil, nil

}
